### PR TITLE
Change wait_for_event time handling

### PR DESCRIPTION
**Pull request by hanzorama**
-because mido messages are being stamped with wall time, the handler is
waiting to receive a message that can only have occurred in the past.
Assigns the wait message/handler message to time=0

### CODE REVIEW

**Comment by adarob** [comment]
The first commit isn't actually necessary because I use a wildcard for the time field of the regex. I should definitely make this more clear in the documentation, however, so thanks for pointing it out!

The second commit looks good. Thanks.

Please revert the first commit and we can pull this in.

**Comment by hanzorama** [comment]
When I fed a mido message as the signal for the wait_for_event, handle_message was still comparing times (msg_str contained the timestamped time)  But when I set times  to zero it worked great. Are you doing something different to the signal you are feeding to the wait_for_event?

**Comment by adarob** [comment]
wait_for_event does not take a mido message as a signal anymore. It takes a MidiSignal object, which enables wildcards for different fields (e.g., any 'note_on' message regardless of note and velocity). However, it might not be a bad idea to let it optionally take a message. Another option is to have a MidiMessageSignal that takes a mido.Message in its constructor and turns it in to a MidiSignal. Thoughts?

**Comment by adarob** [comment]
I integrated the relevant parts of your changes. Thanks!

**Pull request closed without merging**
